### ISSUE TITLE
What's the default tolerance for the seekToTime methods?

### ISSUE THREAD

**Issue by xezero** [Viblast/ios-player-sdk#2]
I'm trying to port over some code in AVPlayer and I require both a precise seek (toleranceAfter and toleranceBefore of kCMTimeZero) as well as a no-tolerance seek (i.e. when I'm scrubbing through the video).

Thanks!

**Comment by ivermolaev** [comment]
Hey @xezero, 

There is no _default_ tolerance because the actual seek point is highly dependent on the stream segments. If the segments are ~ 10 s. long the tolerance can vary up to 10 s, e.g. if you seek the 27th second (having segment length of 10 s.), the actual seek point will be at the 20th second. 
Currently we do not support precise seek but it's something we are aware of and wish to improve if the player proves to be useful for more people!

Cheers!

**Comment by ivermolaev** [comment]
Added seek with tolerance API
